volumes:
  mysqldata:
  php-fpm-socket: #unixドメインソケットを使う為に名前付きボリュームを設定

services:
  # Nginx Webサーバー
  nginx:
    container_name: trackExpenses-web-${ENV_TYPE}
    image: nginx:1.20.0-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - php-fpm-socket:/var/run/php-fpm
    depends_on:
      - php-fpm
    networks:
      - sail

  # Node.js サーバー (フロントエンド用)
  node:
    image: node:18-alpine
    container_name: trackExpenses-node-${ENV_TYPE}
    working_dir: /var/www/html
    tty: true
    volumes:
      - .:/var/www/html
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
    networks:
      - sail

  # PHP-FPMアプリケーションサーバー
  php-fpm:
    container_name: trackExpenses-app-${ENV_TYPE}
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    environment:
      DB_ROOT_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/html
      - php-fpm-socket:/var/run/php-fpm
    depends_on:
      - mysql
    networks:
      - sail

  # MySQLデータベースサーバー
  mysql:
    container_name: trackExpenses-db-${ENV_TYPE}
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME} 
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3307:3306"
    networks:
      - sail

  # Redisサーバー
  redis:
    container_name: trackExpenses-redis-${ENV_TYPE}
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - sail

  # Mailhog (開発用メール確認ツール)
  mailhog:
    container_name: trackExpenses-mailhog-${ENV_TYPE}
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "8025:8025"
    networks:
      - sail
      
  php-cli:
    image: php:8.2-cli
    volumes:
      - .:/var/www/html
    command: ["tail", "-f", "/dev/null"]

networks:
  sail:
    driver: bridge